name: release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 'JEF1056/jade-go-user'
          token: ${{ secrets.PAT }}
      - name: Unzip model
        run: tar -xzf model.tar.gz
      - name: Build code
        run: make build
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/jade-client
          asset_name: jade-client-linux
          asset_content_type: application/zip 

  build_macos:
    # The type of runner that the job will run on
    runs-on: macos-latest
    steps:
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 'JEF1056/jade-go-user'
          token: ${{ secrets.PAT }}
      - name: Unzip model
        run: tar -xzf model.tar.gz
      - name: Build code
        run: make build
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/jade-client
          asset_name: jade-client-macos
          asset_content_type: application/zip 
        
  build_windows:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: 'JEF1056/jade-go-user'
          token: ${{ secrets.PAT }}
      - name: Unzip model
        run: tar -xzf model.tar.gz
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
      - name: Build code
        run: .\build
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/jade-client.exe
          asset_name: jade-client-windows.exe
          asset_content_type: application/zip
